version: '3.4'
services:
  mysqldb:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_USER: sampleuser
      MYSQL_PASSWORD: samplepassword
      MYSQL_DATABASE: sampledb
      REACT_APP_SERVER_PORT: 8000
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./db/sample.sql:/docker-entrypoint-initdb.d/sample.sql
  server:
    build: ./backend
    container_name: node_server_container
    depends_on:
      - mysqldb
    environment:
      MYSQL_HOST_IP: mysqldb
      MYSQL_USER: sampleuser
      MYSQL_PASSWORD: samplepassword
      MYSQL_DATABASE: sampledb
    ports:  
      - 3000:3000
    volumes:
      - ./backend:/app
    links:
      - mysqldb
    command: npm start
  web:
    build: ./frontend
    container_name: react_container
    depends_on:
      - server
    environment:
      API: http://localhost:3000
    ports:  
      - 8080:3000
    volumes:
      - ./frontend:/app
    links:
      - server
    command: npm start