openapi: 3.0.1
info:
  title: react express sample
  description: API description in react express sample.
  version: 1.0.0
  contact:
    email: lokmannicholas@gmail.com
  license:
    name: lokmannicholas
    url: https://github.com/lokmannicholas/react-express-sample
servers:
  - url: http://localhost:3000

paths:
  /plans:
    post:
      tags:
        - "plans"
      summary: "create plans"
      description: "create plans"
      operationId: "createPlans"
      requestBody:
        description: create plans
        content:
          application/json:
            schema:
              type: object
              properties:
                planName:
                  type: string
                features:
                  type: string
                price:
                  type: number
        required: true
      responses:
        200:
          description: Create success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      plan:
                        type: object
                        oneOf:
                          - $ref: '#/components/schemas/Plan'
        500:
          description: Create faile
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Error'
    get:
      tags:
        - "plans"
      summary: "get plans"
      description: "get plans"
      operationId: "getPlans"
      responses:
        200:
          description: Get plans success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      plan:
                        type: array
                        items:
                          $ref: '#/components/schemas/Plan'
        400:
          description: Invalid
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Error'
  /features:
    get:
      tags:
        - "features"
      summary: "get features"
      description: "get features"
      operationId: "getFeatures"
      responses:
        200:
          description: Get features success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      features:
                        type: array
                        items:
                          type: string
        500:
          description: Invalid
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
    Plan:
      type: object
      properties:
        id:
          type: number
        planName:
          type: string
        features:
          type: string
          description: "{\"General\":true,\"Specialist\":false,\"Physiotherapy\":false}"
        price:
          type: number
        updatedAt:
          type: string
        createdAt:
          type: string
    
